### ISSUE TITLE
Extra __next_type__ property causes an error in dev mode

### ISSUE THREAD

**Issue by itsMapleLeaf** [smeijer/next-runtime#11]
Here's what I get:

```
Server Error
Error: Additional keys were returned from `getServerSideProps`. Properties intended for your component must be nested under the `props` key, e.g.:

	return { props: { title: 'My Title', content: '...' } }

Keys that need to be moved: size, timeout, __next_type__.
Read more: https://nextjs.org/docs/messages/invalid-getstaticprops-value
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.renderToHTML
file:///C:/dev/thoughtbucket-next/node_modules/.pnpm/next@11.1.2_bd7797d63db473de6e2318609a63c933/node_modules/next/dist/server/render.js (464:23)
async doRender
file:///C:/dev/thoughtbucket-next/node_modules/.pnpm/next@11.1.2_bd7797d63db473de6e2318609a63c933/node_modules/next/dist/server/next-server.js (1144:38)
async
file:///C:/dev/thoughtbucket-next/node_modules/.pnpm/next@11.1.2_bd7797d63db473de6e2318609a63c933/node_modules/next/dist/server/next-server.js (1236:28)
async
file:///C:/dev/thoughtbucket-next/node_modules/.pnpm/next@11.1.2_bd7797d63db473de6e2318609a63c933/node_modules/next/dist/server/response-cache.js (64:36)
```

If extra metadata is needed on the response, would a symbol key work? Unless it needs to be serializable, then I'm not sure 🤔

**Comment by itsMapleLeaf** [comment]
Ah, this happened when I tried to use a next-runtime handler outside of a `handle()` handler. I guess that should be documented against?

**Comment by smeijer** [comment]
Correct, I'll update the docs today. In v1, I mentioned that those helpers can be used outside the handle function in standard `getServersideProps` functions.

That's no longer true. I used `async_hooks` before to support that, but hooks are buggy and have a performance impact. That's why we now return a `Response` from those helpers, and unwrap them in a later stage.

When not using `handle` you'll be returning `new Response()` from your `getServersideProps`. Next doesn't support that.

We no longer support those handlers outside of next. Those utils were really, really, simple. So I'm not sure if it's worth it to maintain a copy of those in this project, just for the sake of those that want to use `json` but not `handle`.

I'm curious about the use case tho. Why not just turn it into a `handle` with only a `get` method? 

https://github.com/smeijer/next-runtime/commit/f1a5e328a560924bc051ce6a4111296bb5515e4c#diff-db79f1a9685fdf233bd1b68d6ed14d7e39c9224756a817af7bdc15cedf687907

**Comment by smeijer** [comment]
Regarding the extra property I'm adding on Response, I think it should be refactored and be a custom header (`x-next-runtime-type`. That header can be stripped out later.

Here we currently set the prop, could be the header instead:

https://github.com/smeijer/next-runtime/blob/cbf27f9685d6fcc2a8e8205c29677040fe2f66e1/src/responses.ts#L11-L19

And here we could just not transfer the custom header 

https://github.com/smeijer/next-runtime/blob/cbf27f9685d6fcc2a8e8205c29677040fe2f66e1/src/handle.ts#L67-L69

**Comment by smeijer** [comment]
For searchers, I've [pushed the change](https://github.com/smeijer/next-runtime/commit/168b02484e1846a67e61c64d3f7c62bbde862343). This error will now be like:

```
Error: Error serializing props returned from `getServerSideProps` in "/".
Reason: Props must be returned as a plain object from getServerSideProps: `{ props: { ... } }` (received: `[object Undefined]`).
```

**Comment by smeijer** [comment]
Done https://next-runtime.meijer.ws/api/response-helpers#common-mistakes

**Comment by itsMapleLeaf** [comment]
> I'm curious about the use case tho. Why not just turn it into a `handle` with only a `get` method?

Yeah, that's what I ended up doing, I think it was just a mistake 🙃
