### ISSUE TITLE
After form submit, use the data from the method that was submitted to

### ISSUE THREAD

**Issue by itsMapleLeaf** [smeijer/next-runtime#18]
At the moment, it _appears_ as though the new page's props always come from `GET`. If so, this doesn't allow returning and using an error message from a json() in `POST` or `PATCH`. Next.js's data fetching mechanism is kind of blurry to me, so I'm not sure how this should be accomplished 🤔 I might also not be observing this correctly, but I can try to reproduce it later

**Comment by smeijer** [comment]
I've created a demo: https://codesandbox.io/s/next-runtime-18-m4kr1?file=/pages/index.js

And here's the thing. When submitting a plain `<form>`, data from `post` is used for the render.

When submitting a `<Form>`, data from `get` is used for the render, but the `post` data is available in the `onSuccess` handler. I did notice that since we've introduced non-200 status codes, data is not available in the error handler, or at least, not exposed. 

Changing the signature of `onError` should be easy, but it will be a breaking change. So we need to think of a good signature.

Figuring out if and how to make `Form` update the page with data from `post`, will be a hard one, I think.

**Comment by smeijer** [comment]
If we can't figure out how to rerender the current page component with custom data, we might be able to work around it by introducing a `useRouteData` hook, like remix does.

**Comment by smeijer** [comment]
Alternatively, we can create a wrapping component that the user should add to `_app.js`. We can control the render cycle of that component, and thereby force page updates with the data that we want. 

We can even use that to get rid of the usePending hook, and provide that data as a page prop. 🤔

**Comment by itsMapleLeaf** [comment]
I was also thinking that a provider component of some sort would be needed for this, if we can't somehow hack Next.js into working this way. And I think that gives a lot of potential power to the library anyhow; it's a good thing to have.

**Comment by smeijer** [comment]
Yeah, let's just go that route. I don't think it's a crazy requirement.

Only thing we need to decide is, if we want to keep Form working in the current way, or if we make the provider a hard requirement.

(only applies to `Form`, not to `form`)

Thinking out loud, `<Form shallow={true}>` currently works as I would expect. `<Form shallow={false}>` is the one that feels buggy. Part of me feels like we could come away with logging a warning for the non shallow Form

> use the provider if you're expecting different page props after submission?l.

Other me thinks that the user might be confused, and making the provider a hard requirement (by throwing if it's not used) is better for DX, as well as potential future features.

**Comment by itsMapleLeaf** [comment]
Yeah, for the sake of consistency on the user's end and in the library, making the provider required seems like a better idea. We can bump the major if needed

**Comment by MichaelDeBoey** [comment]
Since (one of) the goal(s) of this package is to bring Remix (as much as possible) into the Next.js world, how is Remix doing this?

Do you need a provider in Remix for this?

**Comment by itsMapleLeaf** [comment]
It's probably integrated into react-router somehow. They own the whole framework stack, but we don't 🤷

**Comment by smeijer** [comment]
I wouldn't go as far as saying that the goal of this package is to bring Remix into Next. I don't think that's necessary. I have been inspired by Remix, and I'm likely to keep looking at their function signatures so developers will feel familiar. But saying that the goal is to bring Remix into Next, creates false expectations. The goal is at most to bring the APIs/DX closer to each other.

I mean, technically it's possible. Nextjs supports custom servers, so we could plugin there and handle requests ourselves. Like Remix does. But then we'd be rebuilding Remix, and the user would be better off just switching to them. 

Adding a provider to `_app` is less radical, and something the developer is already familiar with.

**Comment by smeijer** [comment]
I don't expect nor plan to have full feature parity with Remix. I also don't believe that our goals are the same. I just want to provide a simpler API for Next users, that might be able to serve as a middle ground between Next and Remix. I have been inspired by Remix (or more like Ryans caching videos), and I'll probably keep looking at their function signatures (as well as Next's) so that developers feel familiar when using `next-runtime`, but I think that's where it stops. 

Regarding how this feature compares to Remix. Remix has loaders (the `get` api) and actions (the `post` api). They have the limitation that actions must return a `redirect`.

We already support redirects from within the post handler. But our handlers also serve as JSON-API endpoints. Adding the requirement that you _must_ return a redirect, means that the post handler won't be able to return a custom json response (other than what /get would serve). 

I think that's quite the limitation.

**Comment by smeijer** [comment]
We've released https://github.com/smeijer/next-runtime/releases/tag/v2.0.0. Response data is now part of the return value of [`useFormSubmit`](https://next-runtime.meijer.ws/api/use-form-submit), and we offer [`withNextRuntime`](https://next-runtime.meijer.ws/api/with-next-runtime) for those that really need to update the page props after form submit.
